context:
  version: "1.23.0"

package:
  name: yaml-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-${{ version }}.tgz
  sha256: f0b6ec7f169507e9fa31667d0440446d23901b48005d859d99e3de5adef216cf

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - yaml-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language Server for Yaml Files
  homepage: https://github.com/redhat-developer/yaml-language-server
  repository: https://github.com/redhat-developer/yaml-language-server

extra:
  recipe-maintainers:
    - danielnachun
