context:
  version: "1.24.0"
  # oldest EOL LTS, used upstream in .github/workflows/CI.yaml
  node_min: "20"
  # current LTS
  node_build: "22"
  # next LTS
  node_check_max: "26"
  pytest: pytest -vv --tb=long --color=yes -p no:warnings

package:
  name: yaml-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-${{ version }}.tgz
  sha256: 11a321032012131f2ccdf7952dc347ce05291c66931a5de2f449b2dfc81f24b2

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs ${{ node_build }}.*
    - pnpm
    - pnpm-licenses
  run:
    - nodejs >=${{ node_min }}

tests:
  - files:
      recipe:
        - test_yls.py
    requirements:
      run:
        - nodejs ${{ node_min }}.*
        - pytest-lsp
    script:
      - ${{ pytest }}
  - files:
      recipe:
        - test_yls.py
    requirements:
      run:
        - nodejs ${{ node_check_max }}.*
        - pytest-lsp
    script:
      - ${{ pytest }}

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language Server for Yaml Files
  homepage: https://github.com/redhat-developer/yaml-language-server
  repository: https://github.com/redhat-developer/yaml-language-server

extra:
  recipe-maintainers:
    - danielnachun
