context:
  version: "1.22.0"

package:
  name: yaml-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-${{ version }}.tgz
  sha256: 5116c8070d8c39276ca3e3ebb537e839860859586a71eca86fc064ba0ea1913c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - yaml-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language Server for Yaml Files
  homepage: https://github.com/redhat-developer/yaml-language-server
  repository: https://github.com/redhat-developer/yaml-language-server

extra:
  recipe-maintainers:
    - danielnachun
