context:
  version: "1.17.0"

package:
  name: yaml-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-${{ version }}.tgz
  sha256: 12e71607e11c3b62712904245cf3802a9013da74a5093c1ad39c1dca0352f0e1

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - yaml-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language Server for Yaml Files
  homepage: https://github.com/redhat-developer/yaml-language-server
  repository: https://github.com/redhat-developer/yaml-language-server

extra:
  recipe-maintainers:
    - danielnachun
